tasks:
  - init: echo 'Setting up backend...' && npm install
    command: npm start
  - init: echo 'Setting up frontend...' && cd ../writer-db-app && source venv/bin/activate && pip install -r requirements.txt
    command: cd ../writer-db-app" && source venv/bin/activate && python app.py
